default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: heroku_app_mongo_pg_development

test:
  <<: *default
  database: heroku_app_mongo_pg_test

production:
  <<: *default
  database: heroku_app_mongo_pg_production
  #username: myapp
  #password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>